import java.awt.Component;
import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDropEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
/**
 *
 * @author talha
 */
public class MainClient extends javax.swing.JFrame {
    private Exam[] examList;
    private CaptureDesktop cam;
    private String number;
    private String name;
    private String surname;
    private FoxClientUtilities fcu = new FoxClientUtilities();

    ;
    /**
     *
     * Creates new form MainClient
     */
    public MainClient() {

        initComponents();
        //ImageIcon img = new ImageIcon("C:\\Users\\ONURAL\\Desktop\\Tablo.png");
        //setIconImage(img.getImage());
        try {
            examList = fcu.availableExams();
            jList1.setModel(new ExamListModel(examList));
        }catch(IOException e) {
            examList = null;
            jList1.setModel(new ExamListModel(examList));
            jLabel2.setText("Ba\u011Flanamad\u0131.");
            jLabel2.setVisible(true);
        }catch(ClassNotFoundException e) {
            examList = null;
            jLabel2.setText("Eksik dosya.");
            jLabel2.setVisible(true);
        }
        jList1.setModel(new ExamListModel(examList));
        jTextArea1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GozetmenKodu = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Yukleniyor = new javax.swing.JFrame();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        FileChooserFrame = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        GirisEkrani = new javax.swing.JPanel();
        SolPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        surnameTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SagPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        VideoKayitEkrani = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        GozetmenKodu.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        GozetmenKodu.setTitle("Tilki");
        GozetmenKodu.setAlwaysOnTop(true);
        GozetmenKodu.setMinimumSize(new java.awt.Dimension(350, 195));
        GozetmenKodu.setResizable(false);
        GozetmenKodu.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                GozetmenKoduWindowClosing(evt);
            }
        });

        jLabel5.setText("G\u00F6zetmen Kodu");

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        jButton5.setText("S\u0131nav\u0131 Ba\u015F" +
            "lat");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout GozetmenKoduLayout = new javax.swing.GroupLayout(GozetmenKodu.getContentPane());
        GozetmenKodu.getContentPane().setLayout(GozetmenKoduLayout);
        GozetmenKoduLayout.setHorizontalGroup(
            GozetmenKoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GozetmenKoduLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(GozetmenKoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        GozetmenKoduLayout.setVerticalGroup(
            GozetmenKoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GozetmenKoduLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Yukleniyor.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Yukleniyor.setTitle("Tilki");
        Yukleniyor.setAlwaysOnTop(true);
        Yukleniyor.setMinimumSize(new java.awt.Dimension(386, 177));
        Yukleniyor.setResizable(false);

        jLabel12.setText("Y\u00FCkleniyor");

        jLabel13.setText("jLabel13");
        jLabel13.setVisible(false);

        jButton6.setText("Kapat");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout YukleniyorLayout = new javax.swing.GroupLayout(Yukleniyor.getContentPane());
        Yukleniyor.getContentPane().setLayout(YukleniyorLayout);
        YukleniyorLayout.setHorizontalGroup(
            YukleniyorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YukleniyorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(YukleniyorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(YukleniyorLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jButton6)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        YukleniyorLayout.setVerticalGroup(
            YukleniyorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, YukleniyorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FileChooserFrame.setTitle("Tilki");
        FileChooserFrame.setMinimumSize(new java.awt.Dimension(500, 500));

        jFileChooser1.setDragEnabled(true);
        jFileChooser1.setFocusCycleRoot(true);
        jFileChooser1.setMultiSelectionEnabled(true);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        FileChooserFrame.getContentPane().add(jFileChooser1, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tilki");
        setMinimumSize(new java.awt.Dimension(512, 500));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        GirisEkrani.setFont(GirisEkrani.getFont());
        GirisEkrani.setMaximumSize(new java.awt.Dimension(9999, 4819));
        GirisEkrani.setMinimumSize(new java.awt.Dimension(0, 0));
        GirisEkrani.setPreferredSize(new java.awt.Dimension(630, 454));

        SolPanel.setPreferredSize(new java.awt.Dimension(297, 471));

        jLabel1.setText("Numara");

        jLabel3.setText("Soyad");

        jLabel7.setText("Ad");

        surnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameTextFieldActionPerformed(evt);
            }
        });
        surnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                surnameTextFieldKeyPressed(evt);
            }
        });

        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyPressed(evt);
            }
        });

        idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTextFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTextFieldKeyPressed(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("L\u00FCtfen bir s\u0131nav se\u00E7iniz.");

        jButton2.setText("Giri\u015F Yap");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setPreferredSize(new java.awt.Dimension(259, 49));
        jLabel8.setVisible(true);

        jLabel4.setText("<html>S\u0131nava ba\u015Flamak i\u00E7in l\u00FCtfen gerekli bilgileri doldurun ve s\u0131nav\u0131n\u0131z\u0131 se\u00E7iniz.<html/>\n");

        javax.swing.GroupLayout SolPanelLayout = new javax.swing.GroupLayout(SolPanel);
        SolPanel.setLayout(SolPanelLayout);
        SolPanelLayout.setHorizontalGroup(
            SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(SolPanelLayout.createSequentialGroup()
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SolPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(SolPanelLayout.createSequentialGroup()
                                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(SolPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        SolPanelLayout.setVerticalGroup(
            SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SagPanel.setPreferredSize(new java.awt.Dimension(303, 459));

        jList1.setPreferredSize(new java.awt.Dimension(265, 130));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Yenile");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel6.setText("S\u0131navlar");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Durum");
        jLabel2.setVisible(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel11.setText("A\u00E7\u0131klamalar");

        javax.swing.GroupLayout SagPanelLayout = new javax.swing.GroupLayout(SagPanel);
        SagPanel.setLayout(SagPanelLayout);
        SagPanelLayout.setHorizontalGroup(
            SagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SagPanelLayout.createSequentialGroup()
                .addGroup(SagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SagPanelLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SagPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(SagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        SagPanelLayout.setVerticalGroup(
            SagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SagPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(SagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(6, 472));

        javax.swing.GroupLayout GirisEkraniLayout = new javax.swing.GroupLayout(GirisEkrani);
        GirisEkrani.setLayout(GirisEkraniLayout);
        GirisEkraniLayout.setHorizontalGroup(
            GirisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GirisEkraniLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SagPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        GirisEkraniLayout.setVerticalGroup(
            GirisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GirisEkraniLayout.createSequentialGroup()
                .addGroup(GirisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(SolPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GirisEkraniLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SagPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        getContentPane().add(GirisEkrani, "card2");

        VideoKayitEkrani.setPreferredSize(new java.awt.Dimension(526, 500));

        jLabel9.setText("Zaman");

        jScrollPane3.setViewportView(jList2);

        jButton3.setText("G\u00F6zat");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton7.setText("S\u0131nav\u0131 Bitir");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setText("Se\u00E7ili Dosyalar\u0131 Sil");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(8);
        jTextArea2.setRows(5);
        jTextArea2.setText("\n\n\n\n\n\n\tDosyalar\u0131\n\tS\u00FCr\u00FCkleyebilirsiniz.");
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea2.setFocusable(false);

        jLabel14.setText("Ge\u00E7en S\u00FCre");

        jLabel15.setText("<html>S\u0131nav\u0131 bitirmek i\u00E7in g\u00F6ndermek istedi\u011Finiz dosyalar\u0131 g\u00F6zat butonunu <br> kullanarak ya da s\u00FCr\u00FCkleyerek se\u00E7in ve y\u00FCkle tu\u015Funa bas\u0131n.</html>");

        javax.swing.GroupLayout VideoKayitEkraniLayout = new javax.swing.GroupLayout(VideoKayitEkrani);
        VideoKayitEkrani.setLayout(VideoKayitEkraniLayout);
        VideoKayitEkraniLayout.setHorizontalGroup(
            VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VideoKayitEkraniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VideoKayitEkraniLayout.createSequentialGroup()
                        .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VideoKayitEkraniLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VideoKayitEkraniLayout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextArea2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        VideoKayitEkraniLayout.setVerticalGroup(
            VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VideoKayitEkraniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VideoKayitEkraniLayout.createSequentialGroup()
                        .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(VideoKayitEkrani, "card3");
        VideoKayitEkrani.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        name = nameTextField.getText();
        surname = surnameTextField.getText();
        number = idTextField.getText();

        String className = jLabel16.getText();
        if(!(name.isEmpty()) && !(surname.isEmpty()) && !(number.isEmpty()) && !(className.
                                                                                 equals(
                                                                                 "L\u00FCtfen bir s\u0131nav se\u00E7iniz."))) {
            int status = 4;
            try {
                status = fcu.checkIn(name, surname, number, className);
            }catch(IOException ex) {
                jLabel8.setText("Sunucuya eri\u015Filemiyor.");
                jLabel8.setVisible(true);
                examList = null;
                jList1.setModel(new ExamListModel(examList));
                jTextArea1.setText("");
            }
            if(status == 0) {
                jLabel8.setText("Serverda dosya eksik!");
                jLabel8.setVisible(true);
                examList = null;
                jTextArea1.setText("");
                jLabel16.setText("L\u00FCtfen bir s\u0131nav se\u00E7iniz.");
                jList1.setModel(new ExamListModel(examList));
            }else if(status == 1) {
                jList1.setEnabled(false);
                GozetmenKodu.setVisible(true);
                jLabel10.setText("Tekrardan ba\u011Flan\u0131ld\u0131.");
            }else if(status == 2) {
                jList1.setEnabled(false);
                GozetmenKodu.setVisible(true);
                jLabel10.setText("Yeni kay\u0131t.");
            }else {
                jLabel8.setText("Sunucuya eri\u015Filemiyor.");
                jLabel8.setVisible(true);
                examList = null;
                jTextArea1.setText("");
                jLabel16.setText("L\u00FCtfen bir s\u0131nav se\u00E7iniz.");
                jList1.setModel(new ExamListModel(examList));
            }
        }else if(name.isEmpty()) {
            jLabel8.setText("Ad k\u0131sm\u0131 eksik.");
            jLabel8.setVisible(true);
        }else if(surname.isEmpty()) {
            jLabel8.setText("Soyad k\u0131sm\u0131 eksik.");
            jLabel8.setVisible(true);
        }else if(number.isEmpty()) {
            jLabel8.setText("Numara k\u0131sm\u0131 eksik.");
            jLabel8.setVisible(true);
        }else if(className.equals("L\u00FCtfen bir s\u0131nav se\u00E7iniz.")) {
            jLabel8.setText("Yandaki listeden s\u0131nav se\u00E7iniz.");
            jLabel8.setVisible(true);
            jLabel16.setText("L\u00FCtfen bir s\u0131nav se\u00E7iniz.");
        }else
            jLabel8.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            examList = fcu.availableExams();
            jLabel2.setVisible(false);
        }catch(IOException e) {
            examList = null;
            jLabel2.setText("Ba\u011Flanamad\u0131.");
            jLabel2.setVisible(true);
        }catch(ClassNotFoundException e) {
            examList = null;
            jLabel2.setText("Eksik dosya.");
            jLabel2.setVisible(true);
        }
        jList1.setModel(new ExamListModel(examList));
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        int location = jList1.locationToIndex(evt.getPoint());
        if(examList != null && location >= 0) {
            jTextArea1.setText(examList[location].getDescription());
            jLabel16.setText(examList[location].getName());
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        FileChooserFrame.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked
    private tempThread updatingTime;

    private class tempThread extends Thread implements Runnable {
        private volatile boolean running = true;

        public void terminate() {
            running = false;
        }

        @Override
        public void run() {
            running = true;
            try {
                while(running)
                    updateTime();
            }catch(Exception ie) {

            }
        }
    }

    private void updateTime() {
        try {
            //geting Time in desire format
            jLabel9.setText(getTimeElapsed());
            //Thread sleeping for 1 sec
            Thread.currentThread().sleep(1000);
        }catch(Exception e) {
            System.out.println("Exception in Thread Sleep : " + e);
        }
    }
    private long timeAtStart = 0;

    private String getTimeElapsed() {
        long elapsedTime = System.currentTimeMillis() - timeAtStart;
        elapsedTime = elapsedTime / 1000;

        String seconds = Integer.toString((int) (elapsedTime % 60));
        String minutes = Integer.toString((int) ((elapsedTime % 3600) / 60));
        String hours = Integer.toString((int) (elapsedTime / 3600));

        if(seconds.length() < 2)
            seconds = "0" + seconds;

        if(minutes.length() < 2)
            minutes = "0" + minutes;

        if(hours.length() < 2)
            hours = "0" + hours;

        return hours + ":" + minutes + ":" + seconds;
    }
    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton7MouseClicked
    private String zipName;
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        FileChooserFrame.setVisible(false);
        ListModel<String> lm = jList2.getModel();
        List<String> list = jList2.getSelectedValuesList();
        DefaultListModel dlm = new DefaultListModel();
        for(int i = 0; i < lm.getSize(); i++) {
            String a = lm.getElementAt(i);
            if(!list.contains(a))
                dlm.addElement(a);
        }
        jList2.setModel(dlm);

    }//GEN-LAST:event_jButton4MouseClicked

    private void idTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextFieldKeyPressed
        MouseEvent temp;
        temp = new MouseEvent(SolPanel, WIDTH, timeAtStart, ICONIFIED, WIDTH,
                              WIDTH, HEIGHT, rootPaneCheckingEnabled);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jButton2MouseClicked(temp);// TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldKeyPressed

    private void nameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyPressed
        MouseEvent temp;
        temp = new MouseEvent(SolPanel, WIDTH, timeAtStart, ICONIFIED, WIDTH,
                              WIDTH, HEIGHT, rootPaneCheckingEnabled);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jButton2MouseClicked(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldKeyPressed

    private void surnameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surnameTextFieldKeyPressed
        MouseEvent temp;
        temp = new MouseEvent(SolPanel, WIDTH, timeAtStart, ICONIFIED, WIDTH,
                              WIDTH, HEIGHT, rootPaneCheckingEnabled);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jButton2MouseClicked(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_surnameTextFieldKeyPressed

    private void idTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextFieldKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar() > '9' || evt.getKeyChar() < '0')
            evt.consume();
    }//GEN-LAST:event_idTextFieldKeyTyped

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        try {
            int status = fcu.verifyInstructorKey(new String(jPasswordField1.
                    getPassword()));
            if(status == 2)
                jLabel10.setText(
                        "<html>\u015Eifre kabul edilmedi, ve kayda ge\u00E7ildi.<br>"
                        + "L\u00FCtfen tekrar deneyiniz.</html>");
            else if(status == 1) {
                GirisEkrani.setVisible(false);
                GozetmenKodu.setVisible(false);
                VideoKayitEkrani.setVisible(true);
                cam = new CaptureDesktop();
                cam.StartCaptureDesktop(idTextField.getText(), surnameTextField.
                                        getText().charAt(0) + nameTextField.
                                        getText());
                jTextArea2.setDropTarget(new DropTarget() {
                    public synchronized void drop(DropTargetDropEvent evt) {
                        try {
                            evt.acceptDrop(DnDConstants.ACTION_COPY);
                            List<File> droppedFiles = (List<File>) evt.
                                    getTransferable().getTransferData(
                                            DataFlavor.javaFileListFlavor);
                            ListModel<String> lm = jList2.getModel();
                            DefaultListModel dlm = new DefaultListModel();
                            for(File f : droppedFiles)
                                if(f.isFile() && !dlm.contains(f.
                                        getAbsolutePath()))
                                    dlm.addElement(f.getAbsolutePath());
                            for(int i = 0; i < lm.getSize(); i++) {
                                String temp = lm.getElementAt(i);
                                if(!dlm.contains(temp))
                                    dlm.addElement(temp);
                            }
                            jList2.setModel(dlm);
                        }catch(Exception ex) {
                            ex.printStackTrace();
                        }
                    }
                });
                timeAtStart = System.currentTimeMillis();
                updatingTime = new tempThread();
                updatingTime.start();
            }else
                jLabel10.setText("Bilinmeyen hata.");
        }catch(IOException ex) {
            Logger.getLogger(MainClient.class.getName()).log(Level.SEVERE, null,
                                                             ex);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        MouseEvent temp;
        temp = new MouseEvent(SolPanel, WIDTH, timeAtStart, ICONIFIED, WIDTH,
                              WIDTH, HEIGHT, rootPaneCheckingEnabled);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jButton5MouseClicked(temp);        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
        String command = evt.getActionCommand();
        if(command.equalsIgnoreCase("ApproveSelection")) {
            File[] selectedFiles = jFileChooser1.getSelectedFiles();
            ListModel<String> lm = jList2.getModel();
            DefaultListModel dlm = new DefaultListModel();
            for(File f : selectedFiles)
                if(!dlm.contains(f.getAbsolutePath()))
                    dlm.addElement(f.getAbsolutePath());
            for(int i = 0; i < lm.getSize(); i++) {
                String element = lm.getElementAt(i);
                if(!dlm.contains(element))
                    dlm.addElement(element);
            }
            jList2.setModel(dlm);
        }
        jFileChooser1.setSelectedFile(new File(""));
        FileChooserFrame.dispose();
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void GozetmenKoduWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_GozetmenKoduWindowClosing
        // TODO add your handling code here:
        jList1.setEnabled(true);
    }//GEN-LAST:event_GozetmenKoduWindowClosing

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null,
                                                         "S\u0131nav\u0131 bitirmek istedi\u011Finize emin misiniz?",
                                                         "Tilki", 1);
        if(dialogResult == JOptionPane.YES_OPTION) {
            FileChooserFrame.setVisible(false);
            if(cam.status()) {
                cam.StopCaptureDesktop();
                ArrayList<File> filesThatWillUpload = new ArrayList();
                ListModel<String> lm = jList2.getModel();

                String target_file = cam.personName + "." + cam.format; // fileThatYouWantToFilter
                File target_file_object = new File(target_file);
                if(target_file_object.exists()) {
                    filesThatWillUpload.add(new File(target_file));
                    for(int i = 0; i < 100; i++) {
                        target_file_object = new File(i + "_" + target_file);
                        if(target_file_object.exists())
                            filesThatWillUpload.add(new File(
                                    i + "_" + target_file));
                    }
                }
                for(int i = 0; i < lm.getSize(); i++)
                    filesThatWillUpload.add(new File(lm.getElementAt(i)));
                updatingTime.terminate();
                File[] temp = new File[filesThatWillUpload.size()];
                ZipAndUpload zau = new ZipAndUpload(filesThatWillUpload.toArray(
                        temp), number, jLabel16.getText());
                zau.setVisible(true);
                for(Component component : VideoKayitEkrani.getComponents())
                    component.setEnabled(false);
                this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void surnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {

            UIManager.setLookAndFeel(
                    "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        }catch(Exception e) {

        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FileChooserFrame;
    private javax.swing.JPanel GirisEkrani;
    private javax.swing.JFrame GozetmenKodu;
    private javax.swing.JPanel SagPanel;
    private javax.swing.JPanel SolPanel;
    private javax.swing.JPanel VideoKayitEkrani;
    private javax.swing.JFrame Yukleniyor;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField surnameTextField;
    // End of variables declaration//GEN-END:variables

}
