package kasirgalabs;

import static com.sun.javafx.runtime.async.BackgroundExecutor.getTimer;
import java.awt.Color;
import java.awt.Component;
import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDropEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import static java.util.concurrent.TimeUnit.SECONDS;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.UIManager;

public class MainClient extends javax.swing.JFrame {

    private static String ipAddress = "localhost";
    private Exam[] examList;
    private CaptureDesktop cam;
    private RunningProcesses rp;
    private KeyboardActivities ka;
    private static String number;
    private String name;
    private String surname;
    private String instructorKey;
    private String blockedApps;
    private static ZipAndUpload zau;
    private final FoxClientUtilities fcu = new FoxClientUtilities();
    private final TilkiClient tc = new TilkiClient();
    private final Color c = new Color(26, 126, 36);
    private static java.awt.event.ActionListener yenileButtonActionListener;
    private static long timeAtStart = 0;
    private Timer simpleTimer;
    FaceDetection fd ;
    CaptureAudio ca;
    private static final ScheduledExecutorService schedulerForConnectionOFF = Executors.newScheduledThreadPool(
            1);
    private ConnectionOnOff coo = new ConnectionOnOff();

    /**
     *
     * Creates new form MainClient
     */
    public MainClient() {
        examList = tc.listExams();
        initComponents();

        try {
            ImageIcon img = new ImageIcon(getClass().getResource(
                    "images/Tilki.png"));
            setIconImage(img.getImage());
            setLocationRelativeTo(null);
        }
        catch(NullPointerException ex) {
            ClientExceptionHandler.logAnException(ex);
        }

        yenileButtonActionListener = new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenileButtonActionPerformed(evt);
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooserFrame = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        jProgressBar2 = new javax.swing.JProgressBar();
        GirisEkrani = new javax.swing.JPanel();
        SolPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        surnameTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        loginLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        keyField = new javax.swing.JPasswordField();
        keyLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        blockedAppsField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        SagPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        yenileButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        durumLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        VideoKayitEkrani = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dosyaListesi = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        videoKayitGozetmenLabel = new javax.swing.JLabel();
        videoKayitGozetmenField = new javax.swing.JPasswordField();
        keyAcceptedLabel = new javax.swing.JLabel();
        dosyaEksikLabel = new javax.swing.JLabel();

        FileChooserFrame.setTitle("Tilki");
        FileChooserFrame.setMinimumSize(new java.awt.Dimension(500, 500));

        jFileChooser1.setDragEnabled(true);
        jFileChooser1.setFocusCycleRoot(true);
        jFileChooser1.setMultiSelectionEnabled(true);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        FileChooserFrame.getContentPane().add(jFileChooser1, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tilki");
        setMinimumSize(new java.awt.Dimension(630, 360));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        GirisEkrani.setFont(GirisEkrani.getFont());
        GirisEkrani.setMaximumSize(new java.awt.Dimension(9999, 4819));
        GirisEkrani.setMinimumSize(new java.awt.Dimension(0, 0));
        GirisEkrani.setPreferredSize(new java.awt.Dimension(630, 436));

        SolPanel.setPreferredSize(new java.awt.Dimension(297, 471));

        jLabel1.setText("Numara");

        jLabel3.setText("Soyad");

        jLabel7.setText("Ad");

        surnameTextField.setText("Bingöl");
        surnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                surnameTextFieldKeyPressed(evt);
            }
        });

        nameTextField.setText("Begüm");
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyPressed(evt);
            }
        });

        idTextField.setText("123");
        idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTextFieldKeyTyped(evt);
            }
        });

        loginButton.setText("Giri\u015F Yap");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        loginLabel.setForeground(new java.awt.Color(225, 6, 1));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setPreferredSize(new java.awt.Dimension(259, 49));
        loginLabel.setVisible(true);

        jLabel4.setText("<html>S\u0131nava ba\u015Flamak i\u00E7in l\u00FCtfen gerekli bilgileri<br> doldurun ve s\u0131nav\u0131n\u0131z\u0131 se\u00E7in.<html/>\n");

        keyField.setText("123456");
        keyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyFieldActionPerformed(evt);
            }
        });
        keyField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyFieldKeyPressed(evt);
            }
        });

        keyLabel.setText("\u015Eifre");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setText("\u00D6\u011Frenci");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setText("G\u00F6zetmen");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel16.setText("L\u00FCtfen bir s\u0131nav se\u00E7iniz.");

        jLabel10.setText("S\u0131nav");

        blockedAppsField.setText("txt");
        blockedAppsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockedAppsFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Blocked apps");

        javax.swing.GroupLayout SolPanelLayout = new javax.swing.GroupLayout(SolPanel);
        SolPanel.setLayout(SolPanelLayout);
        SolPanelLayout.setHorizontalGroup(
            SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolPanelLayout.createSequentialGroup()
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SolPanelLayout.createSequentialGroup()
                        .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SolPanelLayout.createSequentialGroup()
                                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3)
                                    .addComponent(jSeparator5)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SolPanelLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSeparator2))
                                    .addGroup(SolPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(SolPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(keyField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(blockedAppsField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(keyLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(SolPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(SolPanelLayout.createSequentialGroup()
                                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        SolPanelLayout.setVerticalGroup(
            SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SolPanelLayout.createSequentialGroup()
                        .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SolPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SolPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SolPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SolPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SolPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(SolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blockedAppsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SagPanel.setPreferredSize(new java.awt.Dimension(303, 459));

        jList1.setToolTipText("");
        jList1.setPreferredSize(new java.awt.Dimension(265, 130));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        yenileButton.setText("Yenile");
        yenileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenileButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("S\u0131navlar");

        durumLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        durumLabel.setText("Durum");
        durumLabel.setVisible(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFocusable(false);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel11.setText("A\u00E7\u0131klamalar");

        javax.swing.GroupLayout SagPanelLayout = new javax.swing.GroupLayout(SagPanel);
        SagPanel.setLayout(SagPanelLayout);
        SagPanelLayout.setHorizontalGroup(
            SagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SagPanelLayout.createSequentialGroup()
                .addGroup(SagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                        .addGroup(SagPanelLayout.createSequentialGroup()
                            .addComponent(yenileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(durumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(SagPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel11))
                    .addGroup(SagPanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SagPanelLayout.setVerticalGroup(
            SagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SagPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yenileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durumLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(6, 472));

        javax.swing.GroupLayout GirisEkraniLayout = new javax.swing.GroupLayout(GirisEkrani);
        GirisEkrani.setLayout(GirisEkraniLayout);
        GirisEkraniLayout.setHorizontalGroup(
            GirisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GirisEkraniLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SagPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        GirisEkraniLayout.setVerticalGroup(
            GirisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GirisEkraniLayout.createSequentialGroup()
                .addComponent(SagPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(GirisEkraniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GirisEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 415, Short.MAX_VALUE)
                    .addGroup(GirisEkraniLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(GirisEkrani, "card2");

        VideoKayitEkrani.setPreferredSize(new java.awt.Dimension(558, 466));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Zaman");

        dosyaListesi.setModel(new FileListModel());
        jScrollPane3.setViewportView(dosyaListesi);

        jButton3.setText("G\u00F6zat...");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton7.setText("S\u0131nav\u0131 Bitir");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setText("Se\u00E7ili Dosyalar\u0131 Sil");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(8);
        jTextArea2.setRows(5);
        jTextArea2.setText("\n\n\t                       Dosyalar\u0131\n\t                 S\u00FCr\u00FCkleyebilirsiniz.");
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea2.setFocusable(false);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel14.setText("Ge\u00E7en S\u00FCre");

        jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel15.setText("<html>S\u0131nav\u0131 bitirmek i\u00E7in g\u00F6ndermek istedi\u011Finiz dosyalar\u0131 \"G\u00F6zat\" butonunu kullanarak ya da <br>s\u00FCr\u00FCkleyerek se\u00E7iniz ve \"S\u0131nav\u0131 Bitir\" tu\u015Funa bas\u0131niz.</html>");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jCheckBox1.setText("S\u0131nav\u0131 bitirmeye haz\u0131r\u0131m.");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        videoKayitGozetmenLabel.setText(" G\u00F6zetmen \u015eifresi");

        videoKayitGozetmenField.setEnabled(false);

        javax.swing.GroupLayout VideoKayitEkraniLayout = new javax.swing.GroupLayout(VideoKayitEkrani);
        VideoKayitEkrani.setLayout(VideoKayitEkraniLayout);
        VideoKayitEkraniLayout.setHorizontalGroup(
            VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VideoKayitEkraniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VideoKayitEkraniLayout.createSequentialGroup()
                        .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextArea2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VideoKayitEkraniLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
                            .addGroup(VideoKayitEkraniLayout.createSequentialGroup()
                                .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VideoKayitEkraniLayout.createSequentialGroup()
                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(dosyaEksikLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VideoKayitEkraniLayout.createSequentialGroup()
                                .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(videoKayitGozetmenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(videoKayitGozetmenField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(keyAcceptedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        VideoKayitEkraniLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {videoKayitGozetmenField, videoKayitGozetmenLabel});

        VideoKayitEkraniLayout.setVerticalGroup(
            VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VideoKayitEkraniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(VideoKayitEkraniLayout.createSequentialGroup()
                        .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(VideoKayitEkraniLayout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(VideoKayitEkraniLayout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dosyaEksikLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addComponent(videoKayitGozetmenLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VideoKayitEkraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(keyAcceptedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(videoKayitGozetmenField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VideoKayitEkraniLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(VideoKayitEkrani, "card3");
        VideoKayitEkrani.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        name = nameTextField.getText();
        surname = surnameTextField.getText();
        number = idTextField.getText();
        String className = jLabel16.getText();
        instructorKey = new String(keyField.getPassword());
        blockedApps = blockedAppsField.getText();

        if(!(name.isEmpty()) && !(surname.isEmpty())
                && !(number.isEmpty()) && !(className.equals(
                "L\u00FCtfen bir s\u0131nav se\u00E7iniz."))) {
            if(!(name.isEmpty()) && !(surname.isEmpty())
                    && !(number.isEmpty()) && !(className.equals(
                    "L\u00FCtfen bir s\u0131nav se\u00E7iniz.")) && !instructorKey.
                            isEmpty()) {
                //int status = 4;

                int studentStatus = tc.checkIn(name, surname, Integer.parseInt(
                        number), className);
                int instructorStatus = tc.verifyInstructorKey(className,
                        instructorKey);

                if(instructorStatus == 0) {
                    loginLabel.setText(
                            "<html>\u015Eifre kabul edilmedi. Yanlis asistan sifresi"
                            + "<br>" + "L\u00FCtfen tekrar"
                            + " deneyiniz.</html>");
                }
                else {
                    if(studentStatus == 1) {
                        GirisEkrani.setVisible(false);
                        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                        VideoKayitEkrani.setVisible(true);
                        cam = new CaptureDesktop(idTextField.getText(),
                                surnameTextField.
                                        getText().charAt(0) + nameTextField.
                                getText());
                        rp = new RunningProcesses(blockedApps);
                          ca = new CaptureAudio();
                        fd = new FaceDetection();
                        ka = new KeyboardActivities();
                        Thread t4 = new Thread(fd);
                        Thread t1 = new Thread(cam);
                        Thread t2 = new Thread(rp);
                        Thread t3 = new Thread(ca);

                        Thread t5 = new Thread(ka);

                        t1.start();
                        t2.start();
                        t3.start();
                        t4.start();
                        t5.start();
                        /*
                         * acarsaniz her 10 saniyede bir interneti kesen kodu
                         * calistirir. interneti tekrar acacak kodu nereye
                         * koyacagimi bilemedigimden koymadim.
                         * schedulerForConnectionOFF.scheduleAtFixedRate(coo, 0,
                         * 10, SECONDS);
                         * bu islemi durdurmak icin
                         * schedulerForConnectionOFF.shutdownNow(); denecek,
                         * sonrasinda interneti acmak icin
                         * ConnectionOnOff.openConnections();
                         */

                        jTextArea2.setDropTarget(new DropTarget() {
                            @Override
                            public synchronized void drop(
                                    DropTargetDropEvent evt) {
                                try {
                                    evt.acceptDrop(DnDConstants.ACTION_COPY);
                                    List<File> droppedFiles = (List<File>) evt.
                                            getTransferable().getTransferData(
                                                    DataFlavor.javaFileListFlavor);
                                    FileListModel flm = (FileListModel) dosyaListesi.getModel();
                                    droppedFiles.forEach((f) -> {
                                        flm.addElement(f.getAbsolutePath());
                                    });
                                    if(jCheckBox1.isSelected()) {
                                        jCheckBox1.doClick();
                                    }
                                    dosyaEksikLabel.setText(
                                            flm.getErrorMessage());
                                    dosyaListesi.setModel(flm);
                                }
                                catch(Exception ex) {
                                    jTextArea2.setForeground(Color.RED);
                                    jTextArea2.setText(
                                            "\u0130\u015Fletim sisteminiz"
                                            + " s\u00FCr\u00FCkle b\u0131rak"
                                            + " \u00F6zelli\u011Fini destek"
                                            + "lemiyor.\n");
                                    jTextArea2.append(
                                            "L\u00FCtfen dosya"
                                            + "lar\u0131n\u0131z\u0131 \"G\u00F6z"
                                            + "at\" butonuna t\u0131klayarak"
                                            + " se\u00E7iniz.");
                                    jTextArea2.setDropTarget(null);
                                    //jTextArea2.setEnabled(false);
                                    ClientExceptionHandler.logAnException(ex);
                                }
                            }
                        });
                        timeAtStart = System.currentTimeMillis();
                        simpleTimer = new Timer(1000, new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                jLabel9.setText(getTimeElapsed());
                            }
                        });
                        simpleTimer.start();
                    }
                    else {
                        loginLabel.setText("Bilinmeyen hata.");
                    }
                }
            }
            else if(name.isEmpty()) {
                loginLabel.setText("Ad k\u0131sm\u0131 eksik.");
                loginLabel.setVisible(true);
            }
            else if(surname.isEmpty()) {
                loginLabel.setText("Soyad k\u0131sm\u0131 eksik.");
                loginLabel.setVisible(true);
            }
            else if(number.isEmpty()) {
                loginLabel.setText("Numara k\u0131sm\u0131 eksik.");
                loginLabel.setVisible(true);
            }
            else if(className.equals("L\u00FCtfen bir s\u0131nav se\u00E7iniz.")) {
                loginLabel.setText("Yandaki listeden s\u0131nav se\u00E7iniz.");
                loginLabel.setVisible(true);
                jLabel16.setText("L\u00FCtfen bir s\u0131nav se\u00E7iniz.");
            }
            else if(instructorKey.isEmpty()) {
                loginLabel.setText("G\u00F6zetmen \u015Fifresi eksik.");
                loginLabel.setVisible(true);
            }
            else {
                loginLabel.setVisible(false);
            }
            loginLabel.setVisible(false);
        }
    }//GEN-LAST:event_loginButtonMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if(jCheckBox1.isSelected()) {
            jCheckBox1.doClick();
        }
        FileChooserFrame.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private static String getTimeElapsed() {
        long elapsedTime = System.currentTimeMillis() - timeAtStart;
        elapsedTime = elapsedTime / 1000;

        String seconds = Integer.toString((int) (elapsedTime % 60));
        String minutes = Integer.toString((int) ((elapsedTime % 3600) / 60));
        String hours = Integer.toString((int) (elapsedTime / 3600));

        if(seconds.length() < 2) {
            seconds = "0" + seconds;
        }

        if(minutes.length() < 2) {
            minutes = "0" + minutes;
        }

        if(hours.length() < 2) {
            hours = "0" + hours;
        }

        return hours + ":" + minutes + ":" + seconds;
    }

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if(jCheckBox1.isSelected()) {
            jCheckBox1.doClick();
        }
        FileChooserFrame.setVisible(false);
        FileListModel flm = (FileListModel) dosyaListesi.getModel();
        List<String> list = dosyaListesi.getSelectedValuesList();
        for(int i = 0; i < list.size(); i++) {
            flm.removeElement(list.get(i));
        }
        dosyaEksikLabel.setText(flm.getErrorMessage());
        dosyaListesi.setModel(flm);
    }//GEN-LAST:event_jButton4MouseClicked

    private void idTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextFieldKeyPressed
        MouseEvent temp;
        temp = new MouseEvent(SolPanel, WIDTH, timeAtStart, ICONIFIED, WIDTH,
                WIDTH, HEIGHT, rootPaneCheckingEnabled);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginButtonMouseClicked(temp);
        }
    }//GEN-LAST:event_idTextFieldKeyPressed

    private void nameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyPressed
        // TODO add your handling code here:
        MouseEvent temp;
        temp = new MouseEvent(SolPanel, WIDTH, timeAtStart, ICONIFIED, WIDTH,
                WIDTH, HEIGHT, rootPaneCheckingEnabled);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginButtonMouseClicked(temp);
        }
    }//GEN-LAST:event_nameTextFieldKeyPressed

    private void surnameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surnameTextFieldKeyPressed
        MouseEvent temp;
        temp = new MouseEvent(SolPanel, WIDTH, timeAtStart, ICONIFIED, WIDTH,
                WIDTH, HEIGHT, rootPaneCheckingEnabled);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginButtonMouseClicked(temp);
        }
    }//GEN-LAST:event_surnameTextFieldKeyPressed

    private void idTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextFieldKeyTyped
        if(evt.getKeyChar() > '9' || evt.getKeyChar() < '0') {
            evt.consume();
        }
    }//GEN-LAST:event_idTextFieldKeyTyped

    private void keyFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyFieldKeyPressed
        MouseEvent temp;
        temp = new MouseEvent(SolPanel, WIDTH, timeAtStart, ICONIFIED, WIDTH,
                WIDTH, HEIGHT, rootPaneCheckingEnabled);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginButtonMouseClicked(temp);
        }
    }//GEN-LAST:event_keyFieldKeyPressed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        String command = evt.getActionCommand();
        if(command.equalsIgnoreCase("ApproveSelection")) {
            File[] selectedFiles = jFileChooser1.getSelectedFiles();
            FileListModel flm = (FileListModel) dosyaListesi.getModel();
            for(File f : selectedFiles) {
                flm.addElement(f.getAbsolutePath());
            }
            dosyaEksikLabel.setText(flm.getErrorMessage());
            dosyaListesi.setModel(flm);
        }
        jFileChooser1.setSelectedFile(new File(""));
        FileChooserFrame.dispose();
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()) {
            dosyaEksikLabel.setText("");
            FileListModel flm = (FileListModel) dosyaListesi.getModel();
            if(flm.isEmpty()) {
                dosyaEksikLabel.setText(flm.getErrorMessage());
            }
            if(!flm.areAllFilesExists()) {
                dosyaEksikLabel.setText(flm.getErrorMessage());
                jCheckBox1.doClick();
                return;
            }
            videoKayitGozetmenField.setEnabled(true);
            jButton7.setEnabled(true);
        }
        else {
            videoKayitGozetmenField.setEnabled(false);
            jButton7.setEnabled(false);
            keyAcceptedLabel.setText("");
            videoKayitGozetmenField.setText("");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(jCheckBox1.isSelected()
                && (new String(videoKayitGozetmenField.getPassword())).equals(
                        instructorKey)) {
            FileChooserFrame.setVisible(false);
            ArrayList<File> filesThatWillUpload = new ArrayList<File>(0);
            FileListModel flm = (FileListModel) dosyaListesi.getModel();

            if(cam.status()) {
                cam.StopCaptureDesktop();
            }

            String target_file = cam.getPersonName() + "." + cam.getFormat();
            File target_file_object = new File(target_file);
            if(target_file_object.exists()) {
                filesThatWillUpload.add(new File(target_file));
                for(int i = 0; i < 100; i++) {
                    target_file_object = new File(i + "_" + target_file);
                    if(target_file_object.exists()) {
                        filesThatWillUpload.add(new File(i + "_" + target_file));
                    }
                }
            }
            ArrayList<File> codeFiles = new ArrayList<File>(0);
            for(int i = 0; i < flm.getSize(); i++) {
                codeFiles.add(new File((String) flm.getElementAt(i)));
            }
            simpleTimer.stop();
            File[] temp = new File[filesThatWillUpload.size()];
            File[] temp2 = new File[codeFiles.size()];
            zau = new ZipAndUpload(codeFiles.toArray(temp2),
                    filesThatWillUpload.toArray(
                            temp), number,
                    jLabel16.getText(),
                    instructorKey);
            zau.setVisible(true);
            for(Component component : dosyaListesi.getComponents()) {
                component.setEnabled(false);
            }
            dosyaListesi.setEnabled(false);
            for(Component component : VideoKayitEkrani.getComponents()) {
                component.setEnabled(false);
            }
            VideoKayitEkrani.setEnabled(false);
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
        if(!(new String(videoKayitGozetmenField.getPassword())).equals(
                instructorKey)) {
            keyAcceptedLabel.setText("\u015Eifre yanl\u0131\u015F");
        }
        System.out.println(
                    "girdiii1111");
        ReportWriting rw=new ReportWriting();
        try {
            fd.stop();
            ca.stop();
            System.out.println(
                    "girdiii");
            rw.submitText();
           
        }

        catch(Exception ex) {
            System.out.println(
                    ex);
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void yenileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenileButtonActionPerformed
        try {
            examList = fcu.availableExams();
            durumLabel.setEnabled(true);
            durumLabel.setText("Ba\u011Fland\u0131");
            durumLabel.setForeground(c);
        }
        catch(IOException e) {
            //examList = null;
            durumLabel.setText("Ba\u011Flanamad\u0131");
            durumLabel.setForeground(Color.red);
            durumLabel.setVisible(true);
        }
        catch(ClassNotFoundException e) {
            //examList = null;
            durumLabel.setText("Program dosyalar\u0131n\u0131z eksik.");
            durumLabel.setForeground(Color.red);
            durumLabel.setVisible(true);
        }
        jList1.setModel(new ExamListModel(examList));
        jTextArea1.setText("");
    }//GEN-LAST:event_yenileButtonActionPerformed

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed
        int location = jList1.locationToIndex(evt.getPoint());
        if(examList != null && location >= 0) {
            jTextArea1.setText(examList[location].getDescription());
            jLabel16.setText(examList[location].getName());
        }    }//GEN-LAST:event_jList1MousePressed

    private void blockedAppsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockedAppsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockedAppsFieldActionPerformed

    private void keyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private static class ShutDownHook extends Thread {

        @Override
        public void run() {
            ClientExceptionHandler.sendExceptionsToServer(number);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ShutDownHook hook = new ShutDownHook();
        Runtime.getRuntime().addShutdownHook(hook);

        try {
            UIManager.setLookAndFeel(
                    "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        }
        catch(Exception ex) {
            ClientExceptionHandler.logAnException(ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainClient().setVisible(true);
                Timer timer = new Timer(100, yenileButtonActionListener);
                timer.setRepeats(false);
                timer.start();
            }
        });
    }

    public static String getIpAddress() {
        return ipAddress;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FileChooserFrame;
    private javax.swing.JPanel GirisEkrani;
    private javax.swing.JPanel SagPanel;
    private javax.swing.JPanel SolPanel;
    private javax.swing.JPanel VideoKayitEkrani;
    private javax.swing.JTextField blockedAppsField;
    private javax.swing.JLabel dosyaEksikLabel;
    private javax.swing.JList<String> dosyaListesi;
    private javax.swing.JLabel durumLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private static javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel keyAcceptedLabel;
    private javax.swing.JPasswordField keyField;
    private javax.swing.JLabel keyLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField surnameTextField;
    private javax.swing.JPasswordField videoKayitGozetmenField;
    private javax.swing.JLabel videoKayitGozetmenLabel;
    private static javax.swing.JButton yenileButton;
    // End of variables declaration//GEN-END:variables

}
